// Auto-generated by stim_generation/generate_catch_trials.py
// WARNING: This file is overwritten when you regenerate catch trials.

export const CATCH_TRIALS = [
  {
    "triplet_id": "catch_0",
    "images": [
      "bread-white.png",
      "bread-wholegrain.png",
      "strawberry.png"
    ],
    "correct_choice": 2,
    "pair_reason": "Both are types of sliced bread.",
    "odd_reason": "A strawberry is a fruit, not a baked grain product."
  },
  {
    "triplet_id": "catch_1",
    "images": [
      "grapes-green.png",
      "grapes-red.png",
      "lobster.png"
    ],
    "correct_choice": 2,
    "pair_reason": "Both are types of grapes.",
    "odd_reason": "Lobster is seafood, not a fruit."
  },
  {
    "triplet_id": "catch_2",
    "images": [
      "spinach-raw.png",
      "spinach-prepared.png",
      "chocolate-cake.png"
    ],
    "correct_choice": 2,
    "pair_reason": "Both images show spinach in different forms.",
    "odd_reason": "Chocolate cake is a dessert, not a vegetable."
  },
  {
    "triplet_id": "catch_3",
    "images": [
      "chicken-breast.png",
      "chicken-thigh.png",
      "banana.png"
    ],
    "correct_choice": 2,
    "pair_reason": "Both are cuts of chicken meat.",
    "odd_reason": "A banana is a fruit, not meat."
  },
  {
    "triplet_id": "catch_4",
    "images": [
      "cheese-cheddar.png",
      "cheese-brie.png",
      "apple-raw.png"
    ],
    "correct_choice": 2,
    "pair_reason": "Both are types of cheese.",
    "odd_reason": "An apple is a fruit, not a dairy product."
  },
  {
    "triplet_id": "catch_5",
    "images": [
      "carrot-raw.png",
      "carrot-cooked.png",
      "anchovies.png"
    ],
    "correct_choice": 2,
    "pair_reason": "Both images show carrots prepared differently.",
    "odd_reason": "Anchovies are fish, not vegetables."
  },
  {
    "triplet_id": "catch_6",
    "images": [
      "alfalfa-sprouts.png",
      "spinach-raw.png",
      "chocolate-cake.png"
    ],
    "correct_choice": 2,
    "pair_reason": "Both alfalfa sprouts and spinach are leafy vegetables.",
    "odd_reason": "Chocolate cake is a sweet dessert."
  },
  {
    "triplet_id": "catch_7",
    "images": [
      "apple-pear-nashi.png",
      "banana.png",
      "chicken-breast.png"
    ],
    "correct_choice": 2,
    "pair_reason": "Both apple pear and banana are fruits.",
    "odd_reason": "Chicken breast is meat, not fruit."
  },
  {
    "triplet_id": "catch_8",
    "images": [
      "cheese-cheddar.png",
      "cheese-mozzarella.png",
      "grapes-red.png"
    ],
    "correct_choice": 2,
    "pair_reason": "Both are types of cheese.",
    "odd_reason": "Grapes are fruit, not dairy."
  },
  {
    "triplet_id": "catch_9",
    "images": [
      "carrot-raw.png",
      "spinach-raw.png",
      "lobster.png"
    ],
    "correct_choice": 2,
    "pair_reason": "Both carrot and spinach are vegetables.",
    "odd_reason": "Lobster is seafood, not a vegetable."
  }
];

export default CATCH_TRIALS;