// Auto-generated by stim_generation/prepareimage4experiment.py
// WARNING: This file is overwritten whenever you run the script with
//          the --regen-dense-sample flag. Do not edit by hand if you
//          want your changes to persist.

export const DENSE_ITEMS = [
  "orange.png",
  "tamarind.png",
  "bread-white.png",
  "hot-dog.png",
  "penne.png",
  "couscous.png",
  "fried-noodles.png",
  "cod.png",
  "swiss-chard.png",
  "roast-lamb.png",
  "yam.png",
  "fennel.png",
  "tempeh.png",
  "edamame.png",
  "cabbage-prepared.png",
  "mussels.png",
  "greek-salad.png",
  "waffle.png",
  "mustard-greens.png",
  "butter-chicken.png",
  "fried-chicken.png",
  "tuna.png",
  "barramundi.png",
  "katsu.png",
  "stew.png",
  "almonds.png",
  "cheese-cheddar.png",
  "radicchio.png",
  "brownie.png",
  "alfalfa-sprouts.png"
];

export default DENSE_ITEMS;
