// Auto-generated by stim_generation/prepareimage4experiment.py
// WARNING: This file is overwritten whenever you run the script with
//          the --regen-fixed-triplets flag. Do not edit by hand if you
//          want your changes to persist.

export const FIXED_TRIPLETS = [
  {
    "triplet_id": "fixed_0",
    "images": [
      "alfalfa-sprouts.png",
      "brownie.png",
      "soba-noodles.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_1",
    "images": [
      "alfalfa-sprouts.png",
      "flatbread.png",
      "omelette.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_2",
    "images": [
      "almonds.png",
      "apricot-raw.png",
      "strawberry.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_3",
    "images": [
      "almonds.png",
      "cheese-cheddar.png",
      "radicchio.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_4",
    "images": [
      "anchovies.png",
      "dark-chocolate.png",
      "microgreens.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_5",
    "images": [
      "apple-pear-nashi.png",
      "chayote.png",
      "pomegranate.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_6",
    "images": [
      "apple-pear-nashi.png",
      "chili-con-carne.png",
      "fried-tofu-bowl.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_7",
    "images": [
      "apple-pie.png",
      "carrot-raw.png",
      "lentils.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_8",
    "images": [
      "apple-raw.png",
      "potato-chips.png",
      "spinach-prepared.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_9",
    "images": [
      "apricot-raw.png",
      "garden-salad.png",
      "pomegranate.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_10",
    "images": [
      "artichoke.png",
      "honeydew.png",
      "teriyaki-chicken.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_11",
    "images": [
      "asparagus-prepared.png",
      "sweet-potato-prepared.png",
      "tamarind.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_12",
    "images": [
      "bagel.png",
      "polenta-cake.png",
      "raspberry.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_13",
    "images": [
      "baguette.png",
      "collard-greens.png",
      "sweet-potato-prepared.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_14",
    "images": [
      "baguette.png",
      "ham.png",
      "tempura.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_15",
    "images": [
      "baked-salmon-fillet.png",
      "persimmon.png",
      "spinach-prepared.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_16",
    "images": [
      "bamboo-shoots.png",
      "chapati.png",
      "noodles-wheat.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_17",
    "images": [
      "banana.png",
      "sorghum.png",
      "starfruit.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_18",
    "images": [
      "barramundi.png",
      "edamame.png",
      "tuna.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_19",
    "images": [
      "beef-steak.png",
      "lotus-root.png",
      "pasta-spaghetti.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_20",
    "images": [
      "beetroot-prepared.png",
      "chocolate-cake.png",
      "injera.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_21",
    "images": [
      "bibimbap.png",
      "carrot-raw.png",
      "venison.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_22",
    "images": [
      "blackberry.png",
      "calamari.png",
      "prosciutto.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_23",
    "images": [
      "blueberry.png",
      "octopus.png",
      "waffle.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_24",
    "images": [
      "bok-choy.png",
      "chayote.png",
      "endive.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_25",
    "images": [
      "borrito-bowl.png",
      "mushrooms-button.png",
      "pickled-cucumber.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_26",
    "images": [
      "bread-white.png",
      "dried-mango.png",
      "plantain.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_27",
    "images": [
      "bread-white.png",
      "orange.png",
      "tamarind.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_28",
    "images": [
      "breadstick.png",
      "deli-ham-sliced.png",
      "sorghum.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_29",
    "images": [
      "bulgogi.png",
      "ham.png",
      "okra.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_30",
    "images": [
      "burrito.png",
      "chapati.png",
      "jalapeno.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_31",
    "images": [
      "burrito.png",
      "falafel.png",
      "muffin-english.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_32",
    "images": [
      "burrito.png",
      "kimchi-stew.png",
      "tomato-bruschetta.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_33",
    "images": [
      "butter-chicken.png",
      "fried-chicken.png",
      "mustard-greens.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_34",
    "images": [
      "cabbage-prepared.png",
      "edamame.png",
      "tempeh.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_35",
    "images": [
      "cabbage-raw.png",
      "chilli-pepper.png",
      "sweet-potato-prepared.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_36",
    "images": [
      "cabbage-raw.png",
      "granola.png",
      "salmon.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_37",
    "images": [
      "caesar-salad.png",
      "endive.png",
      "lettuce.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_38",
    "images": [
      "candy.png",
      "fried-rice.png",
      "pesto-pasta.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_39",
    "images": [
      "cannellini-beans.png",
      "raspberry.png",
      "sourdough.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_40",
    "images": [
      "carbonara.png",
      "octopus.png",
      "pinto-beans.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_41",
    "images": [
      "carrot-raw.png",
      "lamb-chop.png",
      "puff-pastry.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_42",
    "images": [
      "casserole.png",
      "fried-rice.png",
      "parsnip.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_43",
    "images": [
      "casserole.png",
      "shiitake-mushrooms.png",
      "tikka-masala.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_44",
    "images": [
      "cheese-brie.png",
      "dumplings.png",
      "rocket-arugula.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_45",
    "images": [
      "chicken-breast.png",
      "date.png",
      "flatbread.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_46",
    "images": [
      "chicken-noodle-soup.png",
      "curry-indian.png",
      "durian.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_47",
    "images": [
      "chicken-noodle-soup.png",
      "lentil-stew.png",
      "yogurt-plain.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_48",
    "images": [
      "chicken-thigh.png",
      "pastry.png",
      "rice-white.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_49",
    "images": [
      "chocolate-cake.png",
      "cracker.png",
      "omelette.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_50",
    "images": [
      "chocolate-peanut-butter-pie.png",
      "flatbread.png",
      "spring-rolls.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_51",
    "images": [
      "cod.png",
      "fried-noodles.png",
      "swiss-chard.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_52",
    "images": [
      "corn.png",
      "kumquat.png",
      "mushrooms-button.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_53",
    "images": [
      "cornbread.png",
      "dried-cherry.png",
      "garlic.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_54",
    "images": [
      "couscous.png",
      "hot-dog.png",
      "penne.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_55",
    "images": [
      "couscous.png",
      "lemon.png",
      "popcorn.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_56",
    "images": [
      "crab.png",
      "kimchi-stew.png",
      "tortilla-corn.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_57",
    "images": [
      "cranberry.png",
      "endive.png",
      "yam.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_58",
    "images": [
      "croissant.png",
      "custard.png",
      "pear-prepared.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_59",
    "images": [
      "croissant.png",
      "muesli.png",
      "napa-cabbage.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_60",
    "images": [
      "cupcake.png",
      "rice-noodles.png",
      "satay.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_61",
    "images": [
      "curry-indian.png",
      "flatbread.png",
      "plum-prepared.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_62",
    "images": [
      "dahl.png",
      "mango-raw.png",
      "tempura.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_63",
    "images": [
      "date.png",
      "tikka-masala.png",
      "wheat.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_64",
    "images": [
      "duck.png",
      "omelette.png",
      "starfruit.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_65",
    "images": [
      "dumplings.png",
      "onion-raw.png",
      "sorbet.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_66",
    "images": [
      "eggs-chicken.png",
      "macaroni-pasta.png",
      "water-chestnut.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_67",
    "images": [
      "eggs-chicken.png",
      "mango-raw.png",
      "satay.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_68",
    "images": [
      "empanada.png",
      "ham.png",
      "portobello-mushrooms.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_69",
    "images": [
      "fennel.png",
      "fried-chicken.png",
      "popcorn.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_70",
    "images": [
      "fennel.png",
      "onion-prepared.png",
      "pad-thai.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_71",
    "images": [
      "fennel.png",
      "roast-lamb.png",
      "yam.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_72",
    "images": [
      "fried-rice.png",
      "microgreens.png",
      "naan.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_73",
    "images": [
      "fruit-leather.png",
      "paella.png",
      "starfruit.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_74",
    "images": [
      "gelato.png",
      "plum-prepared.png",
      "spring-rolls.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_75",
    "images": [
      "greek-salad.png",
      "mussels.png",
      "waffle.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_76",
    "images": [
      "gyoza.png",
      "rocket-arugula.png",
      "turnip.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_77",
    "images": [
      "ham.png",
      "pho.png",
      "scone.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_78",
    "images": [
      "kale-prepared.png",
      "plum-raw.png",
      "tom-yum-soup.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_79",
    "images": [
      "kale-prepared.png",
      "potato-prepared.png",
      "soba-noodles.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_80",
    "images": [
      "katsu.png",
      "stew.png",
      "yam.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_81",
    "images": [
      "kiwi.png",
      "plum-prepared.png",
      "rye.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_82",
    "images": [
      "lime.png",
      "passionfruit.png",
      "squid.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_83",
    "images": [
      "mac-and-cheese.png",
      "pancake.png",
      "raisin.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_84",
    "images": [
      "mac-and-cheese.png",
      "sardines.png",
      "shallot.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_85",
    "images": [
      "mango-raw.png",
      "meatballs.png",
      "pumpkin-soup.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_86",
    "images": [
      "matzo.png",
      "nachos.png",
      "roti.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_87",
    "images": [
      "meatballs.png",
      "scone.png",
      "sorghum.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_88",
    "images": [
      "milk-chocolate.png",
      "peach-raw.png",
      "pizza.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_89",
    "images": [
      "nectarine.png",
      "quail-eggs.png",
      "rocket-arugula.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_90",
    "images": [
      "omelette.png",
      "snow-peas.png",
      "sourdough.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_91",
    "images": [
      "onion-prepared.png",
      "persimmon.png",
      "sashimi.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_92",
    "images": [
      "onion-raw.png",
      "pineapple-prepared.png",
      "quail-eggs.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_93",
    "images": [
      "orange.png",
      "plum-prepared.png",
      "potato-salad.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_94",
    "images": [
      "paella.png",
      "shrimp-spring-rolls.png",
      "tempura.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_95",
    "images": [
      "papaya.png",
      "pinto-beans.png",
      "potato-chips.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_96",
    "images": [
      "pasta-spaghetti.png",
      "sardines.png",
      "tortilla-corn.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_97",
    "images": [
      "prosciutto.png",
      "rice-white.png",
      "venison.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_98",
    "images": [
      "pudding.png",
      "soursop.png",
      "stir-fry.png"
    ],
    "correct_choice": null
  },
  {
    "triplet_id": "fixed_99",
    "images": [
      "soursop.png",
      "tamarind.png",
      "walnuts.png"
    ],
    "correct_choice": null
  }
];

export default FIXED_TRIPLETS;
